"""empty message

Revision ID: 9f4b09900429
Revises: 2a968438fd6b
Create Date: 2019-06-18 10:50:53.379851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f4b09900429'
down_revision = '2a968438fd6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pages', sa.Column('image', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pages', 'image')
    # ### end Alembic commands ###
